name: CI

on:
  workflow_dispatch:

jobs:
  Extract_Branch:
    uses: sandeep4642/github_actions_library/.github/workflows/extract_branch.yml@main
  CI_Workflow:
    needs: [Extract_Branch]
    uses: sandeep4642/github_actions_library/.github/workflows/ci.yml@main
    with:
      javaVersion: 11
    secrets:
      Dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      Dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
  
