name: CI

on:
  workflow_dispatch:
    inputs:
      javaversion:
        default: "11"
        type: number
  
jobs:
  Extract_Branch:
    runs-on: aws-runner
    steps:
      - name: Extract Branch Name
        shell: bash  
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '${{ github.event.inputs.javaversion }}'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -DskipTests clean package
  
  Docker Build:
    runs-on: aws-runner
    needs: [Extract_Branch]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: sandeep4642/spring-boot:${{github.run_number}}
        
