name: CI

on:
  workflow_dispatch:
    inputs:
      javaversion:
        default: "11"
        type: number
  
jobs:
  Extract_Branch:
    uses: sandeep4642/github_actions_library/.github/workflows/extract_branch.yml@main
  CI_Workflow:
    needs: [Extract_Branch]
    uses: sandeep4642/github_actions_library/.github/workflows/ci.yml@main
    with:
      javaVersion: 11
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  
